#####
# Dockerfile for MedPy - Medical image processing in Python
# https://pypi.python.org/pypi/MedPy/
# https://github.com/loli/medpy
#
# Docker container building the ITK library and Python ITK bindings for MedPy (and other use).
# version   0.1
# created   2014-12-07
#####

FROM loli/medpy:dependencies

MAINTAINER Oskar Maier <oskar.maier@googlemail.com>, Dirk Fortmeier

# install MedPy release version
YET-TO-COME!
